#############################################################################
# Makefile for building: segviewer
# Generated by qmake (2.01a) (Qt 4.6.0) on: Tue Mar 16 13:15:53 2010
# Project:  segviewer.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.6.0/bin/qmake -spec /usr/local/Trolltech/Qt-4.6.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile segviewer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.6.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.6.0/include/QtCore -I/usr/local/Trolltech/Qt-4.6.0/include/QtGui -I/usr/local/Trolltech/Qt-4.6.0/include -I../../ocropodium/install/iulib/ocropus-0.4.4/include/iulib -I../../ocropodium/install/iulib/ocropus-0.4.4/include -I../../ocropodium/install/ocropus/ocropus-0.4.4/include/ocropus -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.6.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.6.0/lib -L/home/michaelb/dev/ocropodium/install/iulib/ocropus-0.4.4/lib -liulib -L/home/michaelb/dev/ocropodium/install/ocropus/ocropus-$(OCRVER)/lib -locropus -lQtGui -L/usr/local/Trolltech/Qt-4.6.0/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.6.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		segviewer.cpp \
		ocropusthread.cpp \
		proxythread.cpp \
		imageview.cpp moc_segviewer.cpp \
		moc_ocropusthread.cpp \
		moc_proxythread.cpp \
		moc_imageview.cpp
OBJECTS       = main.o \
		segviewer.o \
		ocropusthread.o \
		proxythread.o \
		imageview.o \
		moc_segviewer.o \
		moc_ocropusthread.o \
		moc_proxythread.o \
		moc_imageview.o
DIST          = /usr/local/Trolltech/Qt-4.6.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/include_source_dir.prf \
		segviewer.pro
QMAKE_TARGET  = segviewer
DESTDIR       = 
TARGET        = segviewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_segviewer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: segviewer.pro  /usr/local/Trolltech/Qt-4.6.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.6.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.6.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.6.0/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.6.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile segviewer.pro
/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.6.0/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.6.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.6.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.6.0/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile segviewer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/segviewer1.0.0 || $(MKDIR) .tmp/segviewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/segviewer1.0.0/ && $(COPY_FILE) --parents segviewer.h ocropusthread.h proxythread.h imageview.h .tmp/segviewer1.0.0/ && $(COPY_FILE) --parents main.cpp segviewer.cpp ocropusthread.cpp proxythread.cpp imageview.cpp .tmp/segviewer1.0.0/ && $(COPY_FILE) --parents segviewer.ui .tmp/segviewer1.0.0/ && (cd `dirname .tmp/segviewer1.0.0` && $(TAR) segviewer1.0.0.tar segviewer1.0.0 && $(COMPRESS) segviewer1.0.0.tar) && $(MOVE) `dirname .tmp/segviewer1.0.0`/segviewer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/segviewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_segviewer.cpp moc_ocropusthread.cpp moc_proxythread.cpp moc_imageview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_segviewer.cpp moc_ocropusthread.cpp moc_proxythread.cpp moc_imageview.cpp
moc_segviewer.cpp: imageview.h \
		proxythread.h \
		ocropusthread.h \
		segviewer.h
	/usr/local/Trolltech/Qt-4.6.0/bin/moc $(DEFINES) $(INCPATH) segviewer.h -o moc_segviewer.cpp

moc_ocropusthread.cpp: ocropusthread.h
	/usr/local/Trolltech/Qt-4.6.0/bin/moc $(DEFINES) $(INCPATH) ocropusthread.h -o moc_ocropusthread.cpp

moc_proxythread.cpp: ocropusthread.h \
		proxythread.h
	/usr/local/Trolltech/Qt-4.6.0/bin/moc $(DEFINES) $(INCPATH) proxythread.h -o moc_proxythread.cpp

moc_imageview.cpp: imageview.h
	/usr/local/Trolltech/Qt-4.6.0/bin/moc $(DEFINES) $(INCPATH) imageview.h -o moc_imageview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_segviewer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_segviewer.h
ui_segviewer.h: segviewer.ui
	/usr/local/Trolltech/Qt-4.6.0/bin/uic segviewer.ui -o ui_segviewer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp segviewer.h \
		imageview.h \
		proxythread.h \
		ocropusthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

segviewer.o: segviewer.cpp segviewer.h \
		imageview.h \
		proxythread.h \
		ocropusthread.h \
		ui_segviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o segviewer.o segviewer.cpp

ocropusthread.o: ocropusthread.cpp ocropusthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ocropusthread.o ocropusthread.cpp

proxythread.o: proxythread.cpp proxythread.h \
		ocropusthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proxythread.o proxythread.cpp

imageview.o: imageview.cpp imageview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageview.o imageview.cpp

moc_segviewer.o: moc_segviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_segviewer.o moc_segviewer.cpp

moc_ocropusthread.o: moc_ocropusthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ocropusthread.o moc_ocropusthread.cpp

moc_proxythread.o: moc_proxythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_proxythread.o moc_proxythread.cpp

moc_imageview.o: moc_imageview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageview.o moc_imageview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

